### ISSUE TITLE
Bug report : Struct writing not reliable

### ISSUE THREAD

**Issue by thedub2001** [Marzogh/SPIFlash#106]
**Hello!**

I'm submitting a bug report, I tried to identify what's going wrong but I cannot fix it...

### Bug report :
**Library version** : 3.0.0
**Branch** : master
**Arduino ID**E : 1.8.4
**OS** : Windows
**Microcontroller** : Arduino-nano (Atmega328P)
**Flash memory module** : W25Q64 freshly erased
**Current behaviour** :
Writing Struct type is not reliable (8% of errors) while writing ByteArray is reliable (0% of error)
**Expected behaviour** :
Writing Struct should be as reliable as writing ByteArray

**Code snippet that reproduces the bug** :
First sketch (not reliable) : part of the code that loops for writing Struct 
```arduino
    for (long k=1;k<10000;k++) {
      addr = flash.getAddress(sizeof(configuration));

      Serial.println();
      Serial.print ("addr = ");
      Serial.println(addr);
      
      if (flash.writeAnything(addr, configuration)){
      }
      else {
        Serial.println ("Struct write failed");
      }
    }
```
_I observe a strange thing on the serial output : "Struct write failed" tends to occur each 12 Struct writings..._

Second sketch (reliable) : part of the code that loops for writing ByteArray 
```arduino
for (long k=1;k<10000;k++) { 
      addr = flash.getAddress(sizeof(pageBuffer));

      Serial.println();
      Serial.print ("addr = ");
      Serial.println(addr);
      
      if (flash.writeByteArray(addr, &pageBuffer[0], SPI_PAGESIZE)) {
       }
      else {
        Serial.println("Page write failed");
      }
      
    }
```

**Comment by Marzogh** [comment]
Thanks for catching this one. It is fixed as of the latest commit (referenced below), and will be rolled out into v3.1.0. 🙂
