### ISSUE TITLE
Bug Report:  Writing struct after Flash erase sector not working.

### ISSUE THREAD

**Issue by cawena** [Marzogh/SPIFlash#112]
Hi,

SPIFlash Version: 3.0.1
Arduino IDE: 1.8.5
OS: Mac 10.13.3
Arduino Board: mega2560
Flash: Winbond: W25Q80BV 1MB

Before I write the struct to flash I do a flash.eraseSector() on page 0.
After check page 0 the values are not stored.
When I do the same with chip erase, all is fine. But I do not always want to delete the whole chip.

The struct:
```
struct CONFIGURATION {
    struct MISC {
        byte tempHigh = 30;            
        byte tempLow = 20;             
        bool parkingMode = false;      
        bool allowDataToBeSent = false;
    } misc;
    struct NETWORK {
        char ssid[50] = "§";           
        char pwd[50] = "§";            
        char userid[50] = "§";         
    } network;
    struct CHARGING_INFO {
        byte interval = 5;             
        byte highChargingDefault = 80; 
    } charging;
} configuration;
```
Save and read :

```
void readConfiguration() {
    flash.readAnything(0, configuration);
}

void saveConfiguration() {
    flash.eraseChip();
    // flash.eraseSector(0);
    flash.writeAnything(0, configuration);
}
```

**Comment by Marzogh** [comment]
Hi guys, Thanks for pointing this out. I've fixed it (I think) in the latest code in the development branch. I've tested it using the new version of Struct_writer.ino in the Examples folder. 🙂 

My apologies for the delay in getting back to you. I came back from a long bushwalking holiday to the start of semester at the University I work at - having 1200 first years to deal with after a month of the wilderness took a bit of getting back into!
