### ISSUE TITLE
feature request: Add different CHIPERASE values

### ISSUE THREAD

**Issue by dberenguer** [Marzogh/SPIFlash#125]
SST26VF064B uses 0xC7 as the CHIPERASE command instead of 0x60. I suggest passing some config values to the constructor or maybe dynamically decide the CHIPERASE command based on the type of memory IC.

**Comment by Marzogh** [comment]
This is something I'm currently working on. 🙂 The code in the development branch can now identify if a chip supports SFDP. (The SST26 series does). I will be adding the ability to get the opcodes from the chip's SFDP tables by the time the next release rolls around. 🙂

**Comment by Marzogh** [comment]
All done and sorted. 😀 The code from the development branch now automatically switches to 0xC7 on the SST26 series and on other ships that support this opcode. I will roll this into v3.2.0.
