### ISSUE TITLE
Compiling getAddressEx.ino example failes when using make

### ISSUE THREAD

**Issue by rnestler** [Marzogh/SPIFlash#19]
When using the [Arduino-Makefile](https://github.com/sudar/Arduino-Makefile) to build the example I get the following errors:
```
libs/SPIFlash/examples/getAddressEx/getAddressEx.ino: In function 'void setup()':
libs/SPIFlash/examples/getAddressEx/getAddressEx.ino:49:16: error: 'getAddresses' was not declared in this scope
   getAddresses();
                ^
libs/SPIFlash/examples/getAddressEx/getAddressEx.ino:50:13: error: 'writeData' was not declared in this scope
   writeData();
             ^
make: *** [build-micro/libs/SPIFlash/examples/getAddressEx/getAddressEx.ino.o] Error 1
```
This is due to missing function prototypes for `getAddresses()` and `writeData()`

**Comment by Marzogh** [comment]
[Arduino-Makefile](https://github.com/sudar/Arduino-Makefile) compatibility will be available from v2.2.1. This is currently in progress and can be obtained from the v2.2.1-w.i.p branch.
