### ISSUE TITLE
error: 'flashCode' was not declared in this scope

### ISSUE THREAD

**Issue by teliot** [Marzogh/SPIFlash#27]
in the file  SPIFlash/examples/TestFlash/TestFlash.ino
after doing the following...
//Uncomment this code block if your code doesn't run to check for Flash error code
i get the error below

command_list.ino: In function 'void setup()':

command_list:96: error: 'flashCode' was not declared in this scope

exit status 1
'flashCode' was not declared in this scope

for both uno & esp8266

**Comment by Marzogh** [comment]
Hi mate,

Thanks for pointing this out. This is a redundant bit of code (it predates the introduction of verbose diagnostic output to Serial) that I seemed to have missed cleaning up - I'll get rid of it in with the next release. Back in the day (pre v2.1.0), the library used to generate a single hex code to indicate any error and that would be printed to Serial with this bit of code. Then I'd have to look up what it meant and try and track down what caused it - which could be a rabbit warren leading to something fairly obscure!

From v2.1.0 onwards, if uncommenting the `#define RUNDIAGNOSTIC` at the top of SPIFlash.cpp (and saving the mod) before running Diagnostics.ino generates a verbose error output to Serial - if there are any errors to catch. The level of verbosity will vary depending on the kind of MCU you are running your code on - each of them has a different amount of system resources to spare. This method makes it easy to catch (almost) every error that could possibly occur and makes debugging a lot easier.

Cheers,

Praj
