### ISSUE TITLE
How to perform error checking?

### ISSUE THREAD

**Issue by clayfreeman** [Marzogh/SPIFlash#28]
I was wondering if it were possible to detect the following:

1. If the SPI chip is wired and initialized correctly.
2. If `SPIFlash::begin()` was called and completed successfully.

I'm modifying a FAT library that uses this library as a backend and it would be useful to know whether the chip and class have been initialized appropriately before calling read/write operations.

**Comment by Marzogh** [comment]
You should be able to do this with the current v2.4.0-w.i.p branch. Call the *****.error() function after any other function call and it will return the error code generated by that function. (Ref: [Wiki page on error codes](https://github.com/Marzogh/SPIFlash/wiki/Error-codes-&-Error-reporting))
