### ISSUE TITLE
Questions about the erasing system

### ISSUE THREAD

**Issue by bernardo-inithaus** [Marzogh/SPIFlash#46]
Two quick questions about erasing sectors:
1) If I call the eraseSector, pass a page to erase, and the offset different than zero, what will happen?
 - Ex: eraseSector(page 0, offset 128) will erase the page 0, starting from byte 128 (maintaining the info in the 0-127 bytes) until the page 15;offset 128, (maintaining the info in the 128-255 bytes)? - Or it will just erase all data in the pages 0 to 15??
2) The erase sector erases all data in 16 pages, what happens if I try to erase starting on the last page? It will overflow and erase data in the 0-14 pages as well?

Thanks!

**Comment by Marzogh** [comment]
Hi @bernardo-inithaus 

If you look at the ReadMe & the wiki for the library or the datasheet from the Winbond cip that you are using, its all explained in detail there :) 

The tl;dr version is this: 

--> eraseSector() erases one 4KB sector(4096 bits - i.e. 16 pages of 256 bits each) - containing the page to be erased.
--> The sectors are numbered 0 onwards containing 16 pages each. Page 0-15 --> Sector 0; Page 16-31 --> Sector 1;......Page 4080-4095 --> Sector 255, and so on...
--> The offset really does not matter, it is available as an option just to keep with the form of the rest of the functions.
--> If for example you pass a command to erase the sector containing the offset 64 on page 541, then sector 33 (size 4KB) gets erased. (Pages 528 - 544 are in Sector 33)
--> If you pass the command to erase offset 81 on page 4095 (on an 8Mbit chip, there are 4096 pages starting at 0 & ending at 4095) then the sector number 255 - which contains pages 4080 to 4095 - is erased.

Hope this helps :)
