### ISSUE TITLE
Not closing SPI Transactions

### ISSUE THREAD

**Issue by kinasmith** [Marzogh/SPIFlash#47]
I'm having issues with this library while working with other SPI devices. 
There are circumstances where it isn't closing the SPI transaction after completing a task, which causes havoc while talking to other devices on the SPI bus that use a different SPI_MODE.
I did some digging and notices several instances where _endSPI has been commented out within the library. Uncommenting the _endSPI() in the _readStat1() function fixed my issues, but I thought ya'll might want to check it out. 
-thanks.

**Comment by Marzogh** [comment]
Hi @kinasmith ,

Thanks for pointing this out. I've already caught this bug as of v2.6.0 (still a work in progress and this should be fixed with the next release. Feel free to test out code from the v2.6.0-w.i.p branch and let me know if anything fails to work.

Cheers!
