### ISSUE TITLE
Cypress S25FL116K

### ISSUE THREAD

**Issue by GumboBeans** [Marzogh/SPIFlash#69]
Would it be possible to get this chip supported?
Looks like some of it works, although it might might be a false positive. 

http://i.imgur.com/Oprl2li.png

**Comment by Marzogh** [comment]
Hi mate, the code on the v3.0.0-w.i.p branch should get you going for now. Please note that this is pre-release code and can change quite dramatically by the time it is ready for release.

**Comment by Marzogh** [comment]
I can confirm that the code on the development branch works with the S25FL116K that is on the Adafruit Feather MO Express. The code is not yet fully documented, but not much has changed w.r.t the basic functions. Feel free to try it out. :)

**Comment by Marzogh** [comment]
#79
