### ISSUE TITLE
Add ability to pick between multiple SPI ports for library comms

### ISSUE THREAD

**Issue by Marzogh** [Marzogh/SPIFlash#70]
STM32 Boards have more than one SPI port. The library has been reported to work with port 1. Would it be possible to let the user code pick which port to use through the library?

**Comment by VitorBoss** [comment]
Thanks for investigate this, this git could help you https://github.com/RRPRIME/STM32

**Comment by Marzogh** [comment]
Cheers, thanks. :)

**Comment by VitorBoss** [comment]
Any update? Also, could you add an option to use native SPI routines? As you can see STM32 is working and really fast.
![2017-07-21](https://user-images.githubusercontent.com/22614869/28485750-26f45d2e-6e52-11e7-88b4-8120dbb988a4.png)

**Comment by Marzogh** [comment]
My apologies for the delay in getting back to you. Work took over my life for a while (in the form of 1251 students who decided to enroll in the First Year genetics course I run!). I've finally got time to look at the library again and I've got the STM32 board - hopefully I'll be able to get this sorted ASAP.

Thanks for running the tests. That is spectacularly fast. Are you using the code from v2.6.0? If yes, would you mind trying the code from the branch v3.0.0-w.i.p? That's the branch I'm going to roll the STM32 support into. Its a complete re-write of the library and so far I've been getting much better I/O speeds from the future v3.0.0 code.

**Comment by VitorBoss** [comment]
Seems to work nice, few functions loose speed(my device is running at 168MHz)
![2017-08-02](https://user-images.githubusercontent.com/22614869/28889662-16c89bca-779b-11e7-831b-393bca3ef49a.png)

**Comment by Marzogh** [comment]
I haven't finished setting up the library to work with the STM32 yet, but the code on the development branch (will go stable once I finish testing the feature across all supported boards) currently supports the ability to use multiple SPI Ports - it's currently been tested with the onboard memory on the Adafruit M0 Feather Express. (It has Cypress 2MBit memory on SPI1.)

**Comment by Marzogh** [comment]
I'm afraid I'm having trouble getting the blue pill board to work with Arduino on my Mac. I have tested the library - as of the latest commit to the development branch - with a STM32 Nucleo-F091RC and it works. Could you please test the code in this branch with the Blue Pill boards that you have?

**Comment by VitorBoss** [comment]
Yes, I will test and comment later

**Comment by VitorBoss** [comment]
Which library are you using for STM32?
I'm using https://github.com/rogerclarkmelbourne/Arduino_STM32 and get a lot of errors

I create PR to fix some errors

**Comment by Marzogh** [comment]
Thanks for the info :) I'll roll the the changes to enable the use of Serial properly across multiple boards into the next release. :) (Ref #88)
