### ISSUE TITLE
Random Error Code

### ISSUE THREAD

**Issue by AMiller10** [Marzogh/SPIFlash#71]
Hi,

I'm using an Arduino Uno with a Winbond 32mB chip, W25Q256FV.  I've been trying to get it to run with no success.  I have already swapped the chip out and that changed nothing.  I've been running the Flash Diagnostics page and it only works on special cases.  I have to comment out the GetID and diagnose functions and upload.  Then I can uncomment GetID and upload.  Then finally I can uncomment diagnose and upload, but I have to have the powerFuncDiag commented out.  If I don't do all those steps I get:

Error Code 0x04
Error Code 0x04
Error Code 0x04.  

Which says could be a wiring problem, but I'm able to get it to work if I use all the steps above (besides PowerDown, that has never passed).  When I do all of that stuff first I get the screenshot that I attached.  
![serial monitor output](https://user-images.githubusercontent.com/29881551/27816133-eeb3042a-60cc-11e7-932c-026ef1720aab.PNG)
 I'm using the sparkfun logic level converter you recommended in the arduino forums and I've checked my wiring 50 times at least.  Would appreciate any help/wondering if there is a bug in the library.  Thank you very much!

**Comment by Marzogh** [comment]
My apologies for the delay in getting back to you. Work took over my life for a while (in the form of 1251 students who decided to enroll in the First Year genetics course I run!). I will take a look at this for you and get back to you by next week. 😄

**Comment by AMiller10** [comment]
No worries.  But awesome, sounds good.  Thanks a lot!

**Comment by Marzogh** [comment]
I'm sorry, but, I have not been able to get my hands on the chip you are using yet. 😒  Could you do me a favour and try running the code form the 'stable' branch and see if that works? 🙏 😃  Its v3.0.0 early alpha level stuff and a lot has changed in the library and I'm hoping I've fixed the bug unwittingly. (I suspect its an address transfer bug) If that doesn't work, I'll just have to wait till AliExpress can get me a couple of the chips via snail mail.

**Comment by Marzogh** [comment]
Any luck?

**Comment by Marzogh** [comment]
I suspect I may have fixed your problem as well when I fixed #91 😄 Can you confirm that the code in the 'stable' branch runs with no problems?
