### ISSUE TITLE
32-bit or 24-bit flash memory

### ISSUE THREAD

**Issue by haapeng** [Marzogh/SPIFlash#84]
Hi,
what I know from ur library support for 32-bit flash memory right?
Is there any possible u make library for 24-bit too?
Thanks mate.

**Comment by Marzogh** [comment]
TBH, I haven't ever played around with a 24-bit flash memory chip. Any recommendations of what chips I can start with?

**Comment by haapeng** [comment]
yeah maybe u can use M25P80 for example

**Comment by Marzogh** [comment]
Thanks. :) I'll get my hands on one and see what I can do. :)

**Comment by Marzogh** [comment]
I've finally gotten around to looking at the datasheet. Could you explain what you mean by 24-bit flash memory as opposed to 8-bit or 32-bit? As far as I can see the M25P80 has 8-bit data storage blocks - just like any other flash memory... (I'm confused)

**Comment by haapeng** [comment]
Oh sorry for the confusion bro. what i meant was 24-bits or 32-bits address. for example cypress flash memory S25FL256S has 32-bits address but the m25p80 has 24-bits address.  so ur library can handle for both bits address?

**Comment by Marzogh** [comment]
It is supposed to handle anything up to 32 bit addresses. 😊

Feel free to test it out and if it doesn’t work let me know and I’ll fix it up for you. I’ve got a few Micron flash memory chips in the mail...

**Comment by Marzogh** [comment]
Also, the Winbond flash chip that the library was originally written for uses 23 bit addresses. 👍🏽

**Comment by Marzogh** [comment]
@haapeng Mate, have you had a chance to test the library with the m25p80? 🙂
