### ISSUE TITLE
A couple of small issues

### ISSUE THREAD

**Issue by lllucius** [Marzogh/SPIFlash#95]
Nothing major and you'll definitely want to verify the choices I made for return value for the three functions missing a return.

[spiflash.txt](https://github.com/Marzogh/SPIFlash/files/1456504/spiflash.txt)

**Comment by Marzogh** [comment]
Hi mate, Thanks for catching the bugs. 😄  

I'd already caught them and they've been fixed in the development branch for a little while now. The changes will be rolling out in the new v3.0.0 release in the next week.
