### ISSUE TITLE
readPage and writePage don't exist - but are listed in API docs

### ISSUE THREAD

**Issue by darkstar007** [Marzogh/SPIFlash#97]
Hi,

These functions (readPage & writePage) are listed in the documentation (i.e. the README.md) but do not actually exist (at least in version 2.7.0)?

Thanks,

Matt

**Comment by Marzogh** [comment]
Thanks for pointing this out. I'm working my way through an overhaul of the API docs and the wiki atm. V3.0.0 will be release in a day or so with updated information in the docs. The wiki will be updated soon.
